apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-proxy-deploy
spec:
  selector:
    matchLabels:
      app: market-proxy-deploy
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: market-proxy-deploy
    spec:
      containers:
      - name: market-proxy-deploy
        image: ghcr.io/asamere/market-proxy:latest
        imagePullPolicy: Always
        # entrypoint:
        #   - "/proxyd"
        envFrom:
          - configMapRef:
              name: market-proxy-config
        env:
          - name: PROXYD_PROXY_API_KEY
            valueFrom:
              secretKeyRef:
                name: market-proxy-secrets
                key: gecko-api-key
          # - name: PROXYD_BASE_PROXY_URL
          #   value: "https://pro-api.coingecko.com"
          # - name: PROXYD_CACHE_TTL_SECS
          #   value: "60"
          # - name: PROXYD_ALLOW_ORIGIN
          #   value: "app.shapeshift.com"
          # - name: PROXYD_ALLOW_HEADERS
          #   value: "Origin, Content-Type, X-Requested-With, Accept"
          # - name: PROXYD_ALLOW_METHODS
          #   value: "GET, HEAD, OPTIONS"
          # - name: PROXYD_LISTEN_ADDR
          #   value: ":80"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "2000m"
        ports:
        - containerPort: 8000
          name: market-proxy
